using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Game.Progression
{
    /// <summary>
    /// Production sets (IP-19). FIELD-001 packet F1-05 ships exactly SET-001/004/006/010/017 with approved
    /// baseline v1 thresholds/effects, generated by scripts/generate_field001_content.py.
    /// </summary>
    public static class ProductionSetCatalog
    {
        public const string ResourcePath = "Content/Sets/ProductionSets";
        private static readonly Regex ProductionId = new Regex("^SET-[0-9]{3}$");

        public static IReadOnlyList<SetDefinition> Create()
        {
            var definitions = FixtureSetCatalog.Load(ResourcePath);
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var definition in definitions)
            {
                var id = definition.Id.ToString();
                if (!ProductionId.IsMatch(id) || !seen.Add(id))
                    throw new InvalidOperationException($"Invalid or duplicate production set '{id}'.");
            }
            return definitions;
        }
    }
}
