using System;
using System.Collections.Generic;
using System.Linq;
using Game.Content;
using Game.Diagnostics;
using Game.Field;
using Game.Movement;
using Game.Presentation;
using UnityEngine;
using UnityEngine.SceneManagement;
using Object = UnityEngine.Object;
using Random = System.Random;

namespace Game.Bootstrap
{
    /// <summary>Visual-only fixture field dressing. Physics remains on the validated scene colliders.</summary>
    public sealed class FieldEnvironmentArtRuntime : IDisposable
    {
        private readonly List<PlaceholderState> _placeholders = new List<PlaceholderState>();
        private readonly List<Collider2D> _obstacleColliders = new List<Collider2D>();
        private readonly Dictionary<Sprite, Rect> _obstacleContactBounds = new Dictionary<Sprite, Rect>();
        private readonly List<Collider2D> _disabledSceneColliders = new List<Collider2D>();
        private readonly List<WallState> _walls = new List<WallState>();
        private readonly List<UnityEngine.Object> _ownedAssets = new List<UnityEngine.Object>();
        private GameObject _root;
        private FieldRoadSurfaceRuntime _roads;
        public FieldRoadLayout RoadLayout { get; private set; }
        private FieldPlatformSurfaceRuntime _platforms;
        public FieldPlatformLayout PlatformLayout { get; private set; }

        public Transform Root => _root != null ? _root.transform : null;
        public IReadOnlyList<Collider2D> ObstacleColliders => _obstacleColliders;
        /// <summary>Obstacles placed for this run (authored or generated by the per-run layout, DECISION-0068).</summary>
        public IReadOnlyList<FieldObstacleDefinition> Obstacles { get; private set; } = Array.Empty<FieldObstacleDefinition>();
        /// <summary>Blob silhouettes placed for this run (field geometry study); empty for other fields.</summary>
        public IReadOnlyList<FieldObstacleShapeDefinition> Shapes { get; private set; } = Array.Empty<FieldObstacleShapeDefinition>();

        public void Initialize(FieldEnvironmentPresentationDefinition definition, ContentRegistry registry,
            FieldEnvironmentDefinition environment, Scene scene, float sideLength, int? layoutSeed = null,
            IReadOnlyList<FieldObstacleExclusion> obstacleExclusions = null)
        {
            if (_root != null) throw new InvalidOperationException("Field environment art is already initialized.");
            if (definition == null || registry == null || environment == null || !scene.IsValid())
                throw new ArgumentException("Field environment art requires definition, registry, environment and scene.");
            if (definition.EnvironmentId != environment.Id)
                throw new InvalidOperationException("Field presentation targets a different environment.");

            var ground = Resolve(definition.Ground, registry, SpriteRole.Tile);
            var fence = Resolve(definition.Fence, registry, SpriteRole.Prop);
            var obstacle = Resolve(definition.Obstacle, registry, SpriteRole.Prop);
            var bush = Resolve(definition.Bush, registry, SpriteRole.Prop);
            var grass = Resolve(definition.Grass, registry, SpriteRole.Prop);
            var column = definition.Column.Id.IsValid ? Resolve(definition.Column, registry, SpriteRole.Prop) : null;
            var barrel = definition.Barrel.Id.IsValid ? Resolve(definition.Barrel, registry, SpriteRole.Prop) : null;
            var rock = definition.Rock.Id.IsValid ? Resolve(definition.Rock, registry, SpriteRole.Prop) : null;
            var shrine = definition.Shrine.Id.IsValid ? Resolve(definition.Shrine, registry, SpriteRole.Prop) : null;
            var transforms = scene.GetRootGameObjects().SelectMany(root => root.GetComponentsInChildren<Transform>(true)).ToList();
            var spawn = RequireUnique(transforms, environment.SpawnPointName);
            var obstacleTransform = RequireUnique(transforms, definition.ObstacleName);

            _root = new GameObject("FieldEnvironmentArt");
            SceneManager.MoveGameObjectToScene(_root, scene);
            try
            {
                foreach (var name in environment.ObstacleNames) HidePlaceholder(RequireUnique(transforms, name));
                if (definition.ArenaSideLength.HasValue) ResizeWalls(transforms, definition.ArenaSideLength.Value);
                CreateGround(ground, sideLength);
                IReadOnlyList<Vector2> interiorObstacles;
                if (definition.RoadLayout != null)
                {
                    HidePlaceholder(obstacleTransform);
                    DisableSceneCollider(obstacleTransform);
                    RoadLayout = FieldRoadLayoutGenerator.Generate(definition.RoadLayout, definition.RoadFallbackLayouts,
                        layoutSeed ?? definition.RoadLayout.ReferenceSeed);
                    _roads = new FieldRoadSurfaceRuntime();
                    var roadArt = definition.RoadLayout.Art;
                    _roads.Initialize(RoadLayout, _root.transform,
                        roadArt == null ? null : Resolve(roadArt.Main, registry, SpriteRole.Tile),
                        roadArt == null ? null : Resolve(roadArt.Branch, registry, SpriteRole.Tile),
                        roadArt == null ? null : Resolve(roadArt.Curb, registry, SpriteRole.Prop));
                    interiorObstacles = Array.Empty<Vector2>();
                }
                else if (definition.PlatformLayout != null)
                {
                    // Field geometry study: round platforms and bridges over a void; nothing blocks movement.
                    HidePlaceholder(obstacleTransform);
                    DisableSceneCollider(obstacleTransform);
                    PlatformLayout = FieldPlatformLayoutGenerator.Generate(definition.PlatformLayout,
                        layoutSeed ?? definition.PlatformLayout.ReferenceSeed);
                    _platforms = new FieldPlatformSurfaceRuntime();
                    var platformArt = definition.PlatformLayout.Art;
                    _platforms.Initialize(PlatformLayout, _root.transform,
                        platformArt == null ? null : Resolve(platformArt.Visual, registry, SpriteRole.Tile));
                    interiorObstacles = Array.Empty<Vector2>();
                }
                else if (definition.BlobLayout != null)
                {
                    // Field geometry study: generated impassable silhouettes replace the prototype scene obstacle.
                    HidePlaceholder(obstacleTransform);
                    DisableSceneCollider(obstacleTransform);
                    Shapes = FieldBlobLayoutGenerator.Generate(definition.BlobLayout, sideLength, spawn.position,
                        layoutSeed ?? definition.BlobLayout.ReferenceSeed, definition.EnvironmentId.ToString());
                    interiorObstacles = CreateBlobObstacles(definition.BlobLayout, Shapes, registry);
                }
                else if (definition.ObstacleLayout != null || definition.ExplicitObstacles.Count > 0)
                {
                    // Authored or per-run layout (DECISION-0068): the prototype scene obstacle is not part of it.
                    HidePlaceholder(obstacleTransform);
                    DisableSceneCollider(obstacleTransform);
                    Obstacles = definition.ObstacleLayout == null ? definition.ExplicitObstacles
                        : FieldObstacleLayoutGenerator.Generate(definition.ObstacleLayout, sideLength, spawn.position,
                            layoutSeed ?? definition.ObstacleLayout.ReferenceSeed, definition.EnvironmentId.ToString(), obstacleExclusions);
                    interiorObstacles = CreateAuthoredObstacles(definition, Obstacles, fence, obstacle, column, barrel, rock,
                        registry);
                }
                else
                {
                    CreateSprite("Stump", obstacle, obstacleTransform.position, definition.ObstacleScale, 0, -2, _root.transform);
                    interiorObstacles = CreateInteriorObstacles(definition, fence, obstacle, spawn.position,
                        obstacleTransform.position, sideLength);
                }
                CreateDecor(definition, bush, grass, shrine, spawn.position, obstacleTransform.position, interiorObstacles, sideLength);
            }
            catch
            {
                Dispose();
                throw;
            }
        }

        public void Dispose()
        {
            _roads?.Dispose(); _roads = null; RoadLayout = null;
            _platforms?.Dispose(); _platforms = null; PlatformLayout = null;
            for (var i = 0; i < _placeholders.Count; i++) _placeholders[i].Restore();
            _placeholders.Clear();
            for (var i = 0; i < _disabledSceneColliders.Count; i++)
                if (_disabledSceneColliders[i] != null) _disabledSceneColliders[i].enabled = true;
            _disabledSceneColliders.Clear();
            _obstacleColliders.Clear();
            _obstacleContactBounds.Clear();
            Obstacles = Array.Empty<FieldObstacleDefinition>();
            Shapes = Array.Empty<FieldObstacleShapeDefinition>();
            for (var i = 0; i < _walls.Count; i++) _walls[i].Restore();
            _walls.Clear();
            if (_root != null)
            {
                _root.SetActive(false);
                if (Application.isPlaying) Object.Destroy(_root); else Object.DestroyImmediate(_root);
                _root = null;
            }
            foreach (var asset in _ownedAssets)
            {
                if (asset == null) continue;
                if (Application.isPlaying) Object.Destroy(asset); else Object.DestroyImmediate(asset);
            }
            _ownedAssets.Clear();
        }

        // Moves the four boundary walls to enclose a square arena of the given side; the scene walls are restored on Dispose.
        private void ResizeWalls(IReadOnlyList<Transform> transforms, float side)
        {
            foreach (var name in new[] { "Wall_Top", "Wall_Bottom", "Wall_Left", "Wall_Right" })
            {
                var wall = RequireUnique(transforms, name);
                var box = wall.GetComponent<BoxCollider2D>();
                if (box == null) throw new InvalidOperationException($"Boundary wall '{name}' requires a BoxCollider2D.");
                _walls.Add(new WallState(wall, box));
                var horizontal = name == "Wall_Top" || name == "Wall_Bottom";
                var thickness = horizontal ? box.size.y : box.size.x;
                var center = (side + thickness) * .5f;
                var span = side + thickness;
                var sign = name == "Wall_Top" || name == "Wall_Right" ? 1f : -1f;
                wall.position = horizontal ? new Vector3(0f, sign * center, wall.position.z)
                    : new Vector3(sign * center, 0f, wall.position.z);
                box.size = horizontal ? new Vector2(span, thickness) : new Vector2(thickness, span);
            }
            Physics2D.SyncTransforms();
        }

        // Each silhouette is a player-only polygon collider under its sprite: the authored library illustration (fixed size and
        // orientation, pivot at the shape origin) or a flat-colour sprite generated from the same points.
        private IReadOnlyList<Vector2> CreateBlobObstacles(FieldBlobLayoutDefinition layout,
            IReadOnlyList<FieldObstacleShapeDefinition> shapes, ContentRegistry registry)
        {
            using var guard = PerfGuard.Measure("FieldEnvironment.CreateBlobObstacles", 150f);
            var playerLayer = LayerMask.NameToLayer("Player");
            if (playerLayer < 0) throw new InvalidOperationException("Player layer is missing.");
            var centers = new List<Vector2>(shapes.Count);
            foreach (var shape in shapes)
            {
                Sprite sprite;
                if (shape.VisualId.IsValid)
                    sprite = Resolve(new ContentRef<SpriteDefinition>(shape.VisualId), registry, SpriteRole.Prop);
                else
                {
                    var style = layout.Styles[shape.Style];
                    sprite = FieldObstacleShapeSprite.Create(shape, style.Fill, style.Outline, layout.PixelsPerUnit,
                        layout.OutlinePixels);
                    _ownedAssets.Add(sprite.texture);
                    _ownedAssets.Add(sprite);
                }
                var renderer = CreateSprite(shape.Id, sprite, shape.Origin, 1f, 0f, -2, _root.transform);
                var collider = renderer.gameObject.AddComponent<PolygonCollider2D>();
                var local = new Vector2[shape.Points.Count];
                for (var i = 0; i < local.Length; i++) local[i] = shape.Points[i] - shape.Origin;
                // Adding the collider next to a sprite pre-fills paths from the sprite's physics shape; only the authored outline counts.
                collider.pathCount = 1;
                collider.SetPath(0, local);
                collider.excludeLayers = ~(1 << playerLayer);
                _obstacleColliders.Add(collider);
                centers.Add(shape.Center);
            }
            return centers;
        }

        private void CreateGround(Sprite sprite, float sideLength)
        {
            var renderer = CreateRenderer("Ground", sprite, Vector3.zero, -100, _root.transform);
            renderer.drawMode = SpriteDrawMode.Tiled;
            renderer.tileMode = SpriteTileMode.Continuous;
            renderer.size = new Vector2(sideLength, sideLength);
        }

        private void CreateDecor(FieldEnvironmentPresentationDefinition definition, Sprite bush, Sprite grass, Sprite shrine,
            Vector2 spawn, Vector2 obstacle, IReadOnlyList<Vector2> interiorObstacles, float sideLength)
        {
            using var guard = PerfGuard.Measure("FieldEnvironment.CreateDecor", 100f);
            var random = new Random(definition.Seed);
            var half = sideLength * .5f - definition.DecorationMargin;
            for (var y = -half; y <= half; y += definition.DecorationSpacing)
            for (var x = -half; x <= half; x += definition.DecorationSpacing)
            {
                var position = new Vector2(
                    x + Range(random, -definition.DecorationJitter, definition.DecorationJitter),
                    y + Range(random, -definition.DecorationJitter, definition.DecorationJitter));
                if (random.NextDouble() > definition.DecorationChance ||
                    Vector2.Distance(position, spawn) < definition.SafeRadius ||
                    Vector2.Distance(position, obstacle) < definition.SafeRadius ||
                    interiorObstacles.Any(item => Vector2.Distance(position, item) < 1.5f))
                    continue;
                if (shrine != null && random.NextDouble() < definition.ShrineChance)
                {
                    CreateSprite("Shrine", shrine, position, 1f, 0f, -8, _root.transform);
                    continue;
                }
                var useBush = random.NextDouble() < definition.BushChance;
                var scale = useBush
                    ? Range(random, definition.BushScaleMin, definition.BushScaleMax)
                    : Range(random, definition.GrassScaleMin, definition.GrassScaleMax);
                var renderer = CreateSprite(useBush ? "Bush" : "Grass", useBush ? bush : grass, position,
                    scale, Range(random, -12, 12), useBush ? -8 : -12, _root.transform);
                renderer.flipX = random.Next(0, 2) == 0;
            }
        }

        private IReadOnlyList<Vector2> CreateInteriorObstacles(FieldEnvironmentPresentationDefinition definition,
            Sprite fence, Sprite stump, Vector2 spawn, Vector2 fixtureObstacle, float sideLength)
        {
            var random = new Random(definition.ObstacleSeed);
            var positions = new List<Vector2>(definition.InteriorObstacleCount);
            var half = sideLength * .5f - definition.DecorationMargin;
            var playerLayer = LayerMask.NameToLayer("Player");
            if (playerLayer < 0) throw new InvalidOperationException("Player layer is missing.");

            for (var index = 0; index < definition.InteriorObstacleCount; index++)
            {
                var accepted = false;
                for (var attempt = 0; attempt < definition.ObstaclePlacementAttempts; attempt++)
                {
                    Vector2 position;
                    if (index < definition.NearObstacleCount)
                    {
                        var angle = Range(random, 0, Mathf.PI * 2);
                        var radius = Mathf.Lerp(definition.SafeRadius + definition.ObstacleSeparation,
                            definition.NearObstacleRadius, Mathf.Sqrt((float)random.NextDouble()));
                        position = spawn + new Vector2(Mathf.Cos(angle), Mathf.Sin(angle)) * radius;
                    }
                    else
                    {
                        position = new Vector2(Range(random, -half, half), Range(random, -half, half));
                    }

                    if (Vector2.Distance(position, spawn) < definition.SafeRadius ||
                        Vector2.Distance(position, fixtureObstacle) < definition.ObstacleSeparation ||
                        positions.Any(item => Vector2.Distance(position, item) < definition.ObstacleSeparation))
                        continue;

                    var useFence = random.NextDouble() < definition.FenceChance;
                    var renderer = CreateSprite(useFence ? "FenceObstacle" : "StumpObstacle",
                        useFence ? fence : stump, position, useFence ? .75f : definition.ObstacleScale,
                        0f, -2, _root.transform);
                    Collider2D collider;
                    if (useFence)
                    {
                        var box = renderer.gameObject.AddComponent<BoxCollider2D>();
                        FitObstacleBox(box, renderer.sprite, definition.FenceColliderWidth,
                            definition.FenceColliderHeight, renderer.transform.localScale.x);
                        collider = box;
                    }
                    else
                    {
                        var circle = renderer.gameObject.AddComponent<CircleCollider2D>();
                        circle.radius = definition.StumpColliderRadius / renderer.transform.localScale.x;
                        collider = circle;
                    }
                    collider.excludeLayers = ~(1 << playerLayer);
                    _obstacleColliders.Add(collider);
                    positions.Add(position);
                    accepted = true;
                    break;
                }
                if (!accepted)
                    throw new InvalidOperationException($"Could not place interior field obstacle {index + 1}.");
            }
            return positions;
        }

        private void DisableSceneCollider(Transform target)
        {
            var collider = target.GetComponent<Collider2D>();
            if (collider == null || !collider.enabled) return;
            collider.enabled = false;
            _disabledSceneColliders.Add(collider);
        }

        // Authored rectangles are the player-only collision boxes; sprites are scaled to the rectangle width.
        private IReadOnlyList<Vector2> CreateAuthoredObstacles(FieldEnvironmentPresentationDefinition definition,
            IReadOnlyList<FieldObstacleDefinition> obstacles, Sprite fence, Sprite stump, Sprite column,
            Sprite barrel, Sprite rock, ContentRegistry registry)
        {
            using var guard = PerfGuard.Measure("FieldEnvironment.CreateObstacles", 100f);
            var playerLayer = LayerMask.NameToLayer("Player");
            if (playerLayer < 0) throw new InvalidOperationException("Player layer is missing.");
            var positions = new List<Vector2>(obstacles.Count);
            foreach (var obstacle in obstacles)
            {
                var isFence = obstacle.Kind == FieldObstacleKind.Fence;
                var sprite = obstacle.VisualId.IsValid
                    ? Resolve(new ContentRef<SpriteDefinition>(obstacle.VisualId), registry, SpriteRole.Prop)
                    : obstacle.Kind switch
                {
                    FieldObstacleKind.Fence => fence,
                    FieldObstacleKind.Column => column,
                    FieldObstacleKind.Barrel => barrel,
                    FieldObstacleKind.Rock => rock,
                    _ => stump
                };
                var position = new Vector2(obstacle.X, obstacle.Y);
                // A tall fence rectangle (FIELD-003 vertical wall) turns the horizontal fence sprite by 90°.
                var upright = isFence && obstacle.Height > obstacle.Width;
                var length = upright ? obstacle.Height : obstacle.Width;
                var thickness = upright ? obstacle.Width : obstacle.Height;
                var scale = length / Mathf.Max(0.0001f, sprite.bounds.size.x) * (isFence ? 1f : definition.ObstacleScale);
                var renderer = CreateSprite(obstacle.Id, sprite, position, scale, upright ? 90f : 0f, -2, _root.transform);
                var box = renderer.gameObject.AddComponent<BoxCollider2D>();
                FitObstacleBox(box, sprite, length, thickness, scale);
                box.excludeLayers = ~(1 << playerLayer);
                _obstacleColliders.Add(box);
                positions.Add(position);
            }
            return positions;
        }

        // The authored rectangle sizes the prop. Its transparent sprite padding must not block the player.
        private void FitObstacleBox(BoxCollider2D box, Sprite sprite, float width, float height, float scale)
        {
            if (!_obstacleContactBounds.TryGetValue(sprite, out var contact))
            {
                var points = new List<Vector2>();
                var minimum = new Vector2(float.PositiveInfinity, float.PositiveInfinity);
                var maximum = new Vector2(float.NegativeInfinity, float.NegativeInfinity);
                for (var shape = 0; shape < sprite.GetPhysicsShapeCount(); shape++)
                {
                    points.Clear();
                    sprite.GetPhysicsShape(shape, points);
                    foreach (var point in points)
                    {
                        minimum = Vector2.Min(minimum, point);
                        maximum = Vector2.Max(maximum, point);
                    }
                }
                contact = float.IsPositiveInfinity(minimum.x)
                    ? new Rect(sprite.bounds.min, sprite.bounds.size)
                    : Rect.MinMaxRect(minimum.x, minimum.y, maximum.x, maximum.y);
                _obstacleContactBounds.Add(sprite, contact);
            }

            var bounds = sprite.bounds;
            box.size = new Vector2(width / scale * contact.width / bounds.size.x,
                height / scale * contact.height / bounds.size.y);
            box.offset = new Vector2(width / scale * (contact.center.x - bounds.center.x) / bounds.size.x,
                height / scale * (contact.center.y - bounds.center.y) / bounds.size.y);
        }

        private void HidePlaceholder(Transform target)
        {
            var placeholder = target.GetComponent<PlaceholderColorRenderer>();
            var renderer = target.GetComponent<SpriteRenderer>();
            _placeholders.Add(new PlaceholderState(placeholder, renderer));
            if (placeholder != null) placeholder.enabled = false;
            if (renderer != null) renderer.enabled = false;
        }

        private static SpriteRenderer CreateSprite(string name, Sprite sprite, Vector2 position, float scale,
            float rotation, int sortingOrder, Transform parent)
        {
            var renderer = CreateRenderer(name, sprite, position, sortingOrder, parent);
            renderer.transform.localScale = Vector3.one * scale;
            renderer.transform.rotation = Quaternion.Euler(0, 0, rotation);
            return renderer;
        }

        private static SpriteRenderer CreateRenderer(string name, Sprite sprite, Vector2 position, int sortingOrder,
            Transform parent)
        {
            var item = new GameObject(name);
            item.transform.SetParent(parent, false);
            item.transform.position = new Vector3(position.x, position.y, 0);
            var renderer = item.AddComponent<SpriteRenderer>();
            renderer.sprite = sprite;
            renderer.sortingOrder = sortingOrder;
            return renderer;
        }

        private static Sprite Resolve(ContentRef<SpriteDefinition> reference, ContentRegistry registry, SpriteRole role)
        {
            var definition = reference.Resolve(registry);
            definition.RequireRole(role);
            return definition.Sprite;
        }

        private static Transform RequireUnique(IEnumerable<Transform> transforms, string name)
        {
            var matches = transforms.Where(item => item.name == name).ToList();
            if (matches.Count != 1) throw new InvalidOperationException($"Field art binding '{name}' must occur exactly once.");
            return matches[0];
        }

        private static float Range(Random random, float minimum, float maximum) =>
            minimum + (float)random.NextDouble() * (maximum - minimum);

        private readonly struct WallState
        {
            private readonly Transform _transform;
            private readonly BoxCollider2D _box;
            private readonly Vector3 _position;
            private readonly Vector2 _size;

            public WallState(Transform transform, BoxCollider2D box)
            {
                _transform = transform; _box = box; _position = transform.position; _size = box.size;
            }

            public void Restore()
            {
                if (_transform != null) _transform.position = _position;
                if (_box != null) _box.size = _size;
            }
        }

        private readonly struct PlaceholderState
        {
            private readonly PlaceholderColorRenderer _placeholder;
            private readonly SpriteRenderer _renderer;
            private readonly bool _placeholderEnabled;
            private readonly bool _rendererEnabled;

            public PlaceholderState(PlaceholderColorRenderer placeholder, SpriteRenderer renderer)
            {
                _placeholder = placeholder;
                _renderer = renderer;
                _placeholderEnabled = placeholder != null && placeholder.enabled;
                _rendererEnabled = renderer != null && renderer.enabled;
            }

            public void Restore()
            {
                if (_placeholder != null) _placeholder.enabled = _placeholderEnabled;
                if (_renderer != null) _renderer.enabled = _rendererEnabled;
            }
        }
    }
}
